language: ruby
cache:
  directories:
rvm:
  - "2.6.2"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
services:
  - postgresql
addons:
  postgresql: "9.3"
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
